# Generated by Django 4.2.19 on 2025-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, unique=True)),
                ('ankle', models.FloatField(blank=True, null=True)),
                ('armLength', models.FloatField(blank=True, null=True)),
                ('bicep', models.FloatField(blank=True, null=True)),
                ('calf', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('forearm', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('hip', models.FloatField(blank=True, null=True)),
                ('legLength', models.FloatField(blank=True, null=True)),
                ('shoulderBreadth', models.FloatField(blank=True, null=True)),
                ('shoulderToCrotch', models.FloatField(blank=True, null=True)),
                ('thigh', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('wrist', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
